# Generated by Django 3.2.5 on 2022-03-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_doctor_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
