# Generated by Django 4.0.4 on 2022-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220507_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_img',
            field=models.ImageField(default='No Image', upload_to='images/'),
        ),
    ]
