# Generated by Django 3.2.5 on 2022-05-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_patient_patient_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_name',
        ),
    ]
